config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get "/", to: "portafolio#home"
  get "/projects", to: "portafolio#projects"
  get "/contact", to: "portafolio#contact"
  get "/gracias", to: "portafolio#gracias"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/portafolio_controller.rb
class PortafolioController < ApplicationController
    def home
    end

    def projects
    end

    def contact
    end

    def gracias
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portafolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
  </head> 

  <body>
  <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <%= link_to 'Home', '/', class: 'text-decoration' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
              <%= link_to 'Projects', projects_path, class: 'nav-link' %> 
            </li>            
            <li class="nav-item">
              <%# <a class="nav-link" href="#">contact</a> %>
              <%= link_to 'Contact', contact_path, class: 'nav-link' %>
            </li>  
            <li class="nav-item">              
              <%= link_to 'Gracias', gracias_path, class: 'nav-link' %>
            </li>           
          </ul>
        </div>
      </div>
    </nav>


    <div class="container">
      <%= yield %>
    </div>


    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <%= link_to 'Home', '/', class: 'text-decoration' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%# <a class="nav-link active" aria-current="page" href="#">Home</a> %>
              <%= link_to 'Projects', projects_path, class: 'nav-link' %> 
            </li>            
            <li class="nav-item">
              <%# <a class="nav-link" href="#">contact</a> %>
              <%= link_to 'Contact', contact_path, class: 'nav-link' %>
            </li>
             <li class="nav-item">              
              <%= link_to 'Gracias', gracias_path, class: 'nav-link' %>
            </li>            
          </ul>
        </div>
      </div>
    </nav>
  </body>
</html>

app/views/portafolio/contact.html.erb
<p>Si necesitas ayuda...<p>
<h2>Contactame</h2>
 

<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">Nunca compartiremos tu email.</div>
  </div>

  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Nombre</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>

  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">¿Quiere recibir mas información?</label>
  </div>


  <div class="mb-3  ">
    <label for="exampleFormControlTextarea1" class="form-label">Detalles</label>
    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
  </div>


  <button type="submit" class="btn btn-primary">Enviar</button>
</form>

app/views/portafolio/gracias.html.erb
<h1>Todo esto es posible gracias </h1>


<div class="container text-center">
    <div class="">
    <h2>Al mejor profesor</h2>
    <%= image_tag 'profe.jpg', size: "200" %>
    </div>
</div>

<div class="container text-center">
    <div class="">
    <h2>La mejor ayudante</h2>
    <%= image_tag 'naty.png', size: "200" %>
    </div>
</div>


<div class="container text-center">
    <div class="">
    <h2>Los mejor compañeros</h2>
    <%= image_tag 'companeros.png', size: "200" %>
    </div>
</div>

app/views/portafolio/home.html.erb
<div class="container text-center">
    <div class="">
    <h1>Eduardo Concha</h1>
    <h3>Tus ideas, desarrolladas con las mejores tecnologias</h3>
    </div>
</div>

<div class="container text-center">
    <div class="">
    <%= image_tag 'ruby.jpg', size: "150" %>
    <%= image_tag 'rails.png', size: "150"  %>
    <%= image_tag 'bootstrap.png', size: "150"  %>
    <%= image_tag 'htmlcss.png', size: "150" %>
    </div>
</div>

app/views/portafolio/projects.html.erb
<h2>Proyectos</h2>



<div class="container">
<div class="row">

<div class="col-sm mt-5">
<div class="card" >
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <%= image_tag 'proyecto1.png', class: '' %>
  <div class="card-body">
    <h5 class="card-title">Coffe</h5>
    <p class="card-text">Proyecto html, css y bootstrap.</p>
    <a href="#" class="btn btn-primary">Hermoso</a>
  </div>
</div>
</div>


<div class="col-sm mt-5">
<div class="card" >
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <%= image_tag 'proyecto2.png', class: '' %>
  <div class="card-body">
    <h5 class="card-title">Cuppon</h5>
    <p class="card-text">Proyecto html, css y bootstrap.</p>
    <a href="#" class="btn btn-primary">Maravilloso</a>
  </div>
</div>
</div>

</div>
</div>








<div class="container mt-5">
<div class="row  ">

<div class="col-sm mt-5">
<div class="card" >
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <%= image_tag 'proyecto3.png', class: '' %>
  <div class="card-body">
    <h5 class="card-title">Iguana</h5>
    <p class="card-text">Proyecto html, css y bootstrap.</p>
    <a href="#" class="btn btn-primary">Pura Vida</a>
  </div>
</div>
</div>


<div class="col-sm mt-5">
<div class="card" >
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <%= image_tag 'proyecto4.png', class: '' %>
  <div class="card-body">
    <h5 class="card-title">Ricomida</h5>
    <p class="card-text">Proyecto html, css y bootstrap.</p>
    <a href="#" class="btn btn-primary">Me encanta</a>
  </div>
</div>
</div>

</div>
</div>